
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/go/bin" ] ; then
    PATH="$HOME/go/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.scripts" ] ; then
    PATH="$HOME/.scripts:$PATH"
fi

# set PATH so it includes golang if it exists
if [ -d "/usr/local/go/bin" ] ; then
    PATH="/usr/local/go/bin:${PATH}"
fi

export NAP_CONFIG="$HOME/.nap/config.yaml"
export NAP_HOME="$HOME/.nap"

if [ ! $SPIN ]; then
    export GOROOT="/usr/local/go"
    export GOPATH="$HOME/go"
fi
