
# Function to add a directory to the PATH variable
add_to_path() {
    local dir="$1"
    if [ -d "$dir" ]; then
        PATH=$(echo $PATH | sed -e "s#:$dir:##g")
        PATH="$dir:$PATH"
    fi
}

add_to_path "$HOME/bin"
add_to_path "$HOME/go/bin"
add_to_path "$HOME/run/bin"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.scripts"
add_to_path "/usr/local/go/bin"
# add_to_path "$HOME/.rd/bin"
add_to_path "/usr/local/share/dotnet"
add_to_path "/usr/local/bin"
add_to_path "/opt/bolt/bin"
add_to_path "$HOME/.krew/bin"
add_to_path "/opt/homebrew/opt/mysql-client/bin"

# Bolt Flags
export BOLT_UPDATE_NOTIFICATIONS_ENABLED="true"

# command -v pyenv &> /dev/null && PATH=$(pyenv root)/shims:$PATH

# Added by OrbStack: command-line tools and integration
if [ -d "~/.orbstack" ]; then
    source ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi
