autoload -U compinit; compinit

command -v starship &> /dev/null && eval "$(starship init zsh)"
[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
[[ -x /opt/dev/dev.sh ]] && source /opt/dev/dev.sh
[[ -x /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

export EDITOR="code -w"

###
## Aliases
###
alias k='kubectl'
alias sc='systemctl'
alias jc='journalctl'
command -v bat &> /dev/null && alias cat=bat
command -v batcat &> /dev/null && alias cat=batcat

###
## SHOPIFY
###
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/campbel/.kube/config:/Users/campbel/.kube/config.shopify.cloudplatform
for file in /Users/campbel/src/github.com/Shopify/cloudplatform/workflow-utils/*.bash; do source ${file}; done
kubectl-short-aliases
