autoload -U compinit; compinit

eval "$(starship init zsh)"

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
if [ -e /Users/campbel/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/campbel/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# cloudplatform: add Shopify clusters to your local kubernetes config
# export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/campbel/.kube/config:/Users/campbel/.kube/config.shopify.cloudplatform
# for file in /Users/campbel/src/github.com/Shopify/cloudplatform/workflow-utils/*.bash; do source ${file}; done
# kubectl-short-aliases

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

alias k='kubectl'
alias cat=bat

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

export EDITOR="code -w"
