home: /Users/campbel/.nap
file: snippets.json
currentFolder: 2
default_language: go
theme: nord
primary_color: '#AFBEE1'
primary_color_subdued: '#64708D'
bright_green: '#BCE1AF'
green: '#527251'
bright_red: '#E49393'
red: '#A46060'
foreground: "7"
background: "0"
gray: "240"
black: '#373B41'
white: '#FFFFFF'
