#!/usr/bin/env bash

echo "Setting up Linux"

if [ "$SPIN" ]; then
    true
else
    sudo apt update -y
    sudo apt install -y \
        curl \
        zsh \
        git
    sudo apt upgrade -y
    # Install starship
    chsh -s /usr/bin/zsh
fi

sudo apt install -y \
    bat

sudo /bin/sh starship/install.sh -y
