#!/usr/bin/env bash

echo "Setting up macOS"

brew install \
    bat \
    curl \
    git \
    zsh \
    neovim \
    ripgrep \
    fzf \
    lazygit \
    starship

brew install --cask font-fira-code-nerd-font
brew install --cask claude-code

sudo gem install colorls
