#!/usr/bin/env bash

echo "Setting up macOS"

brew install \
    bat \
    curl \
    git \
    zsh \
    neovim \
    starship

brew install --cask font-fira-code-nerd-font

sudo gem install colorls
